name: TAB
version: @version@
author: NEZNAMY
main: me.neznamy.tab.platforms.bukkit.Main
api-version: 1.13
softdepend: [PlaceholderAPI, Vault, LuckPerms, Essentials, LibsDisguises, ProtocolSupport, ViaVersion, floodgate]
website: "https://github.com/NEZNAMY/TAB"
description: @description@
commands:
  tab:
    description: Plugin's main command