name: Bug Report
description: Plugin does not work as described.
labels: ["Type: Bug"]
body:
  - type: input
    attributes:
      label: Server version
      description: Version and type of used server software where TAB is installed.
      placeholder: Spigot 1.18.1
    validations:
      required: true

  - type: input
    attributes:
      label: TAB version
      description: Full version in numbers, "latest" is not a version.
      placeholder: 3.0.2
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: How the plugin behaves
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: How the plugin is supposed to behave instead with your configuration.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: What to do in order to reproduce this issue
      placeholder: |
        Step 1: ..
        Step 2: ..
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional info
      description: Anything else you want to provide that will help in resolving the issue faster, such as screenshots or videos.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Checklist
      description: Let's make sure this report is valid
      options:
        - label: I am running latest version of the plugin
          required: true
        - label: I have read the wiki to make sure it's not an issue with configuration
          required: true
        - label: I ticked all of the boxes without actually reading them
          required: false
        - label: I have read the Compatibility wiki page and am not trying to run the plugin on an unsupported server version / platform
          required: true
        - label: I am willing to cooperate to get this issue resolved faster, including providing any additional information requested or testing new builds
          required: true