direction: COLUMNS

fixed-slots:
  - '1:&c&lLOVETAB'
  - '2:1.16.2 - 1.16.4'
  - '4:&8------------'
  - '5:&6Server1'
  - '6:&8------------'
  - '19:&8------------'
  - '20:&eMore info here'
  - '21:&eVote for our'
  - '24:&8------------'
  - '25:&5Server2'
  - '26:&8------------'
  - '39:&8------------'
  - '40:&eand here too'
  - '41:&eserver to make'
  - '44:&8------------'
  - '59:&8------------'
  - '61:&eit much coolier'
  - '64:&8------------'

parent-groups:
  MainGroup1:
    condition: server1condition
    slots:
      - '7-22'
    child-groups:
      - StaffGroup
      - PlayerGroup
  MainGroup2:
    condition: server2condition
    slots:
      - '27-38'
child-groups:
  StaffGroup:
    title: '&4---STAFF---'
    condition: group=admin || group=moder
  PlayerGroup:
    title: '&8---PLAYERS---'